# Conceptual framework

### How can we conceptualize evaluation? (or: imputation as a sociotechical system)

<!-- ### Computational evaluation, verification and validation  -->
<!-- [TODO: edit] -->
In this section we will learn how imputation methodology can be evaluated as a 'system'.
The system life cycle framework offers terminology and tools for systems engineering: to build, develop and evaluate systems.
From this perspective, imputation workflows are 'sociotechnical systems' specifically.
<!-- TODO: add refs Trist and Emery? -->
A sociotechnical system is a collection of interrelated components (software, hardware, and people) that delivers services to users [@sommerville2015].
<!-- In contrast to a purely technical system, a sociotechnical system is a collection of interrelated components that delivers services to users [@sommerville2015, p. 556]. -->
In contrast to technical computer-based systems, sociotechnical systems contain both technical components as well as human operators.
<!--  -->
<!-- Sociotechnical systems "include one or more technical systems but, crucially, also people" [@sommerville2015, p. 552], and their success relies on the joint functioning of the system components [@sommerville2015, p. 556]. -->
<!-- Software systems can be categorized into 'technical computer-based systems' and 'sociotechnical systems' [@sommerville2015, p. 552]. -->
Imputation workflows, therefore, are sociotechical systems.
They contain not just software (e.g., `mice`), but also the imputer who runs the imputations.

The inclusion of a 'human in the loop', has three noteworthy consequences. 
<!-- Sociotechnical systems have three characteristics, namely:  -->
Firstly, sociotechnical systems have non-deterministic outputs, resulting from human operators who may differ in the choices they make.
Secondly, they have emergent properties of the system as a whole, which only becomes apparent when integrating the separate components.
And thirdly, the success criteria of sociotechnical systems are subjective, depending on the context of evaluation: "it is practically impossible to have a complete understanding, in advance, of their behavior" [@sommerville2015, p. 558].
<!-- [@sommerville2015, p. 558]. -->
So, the success of sociotechnical systems as a whole relies on the joint functioning of its components, plus the context of its application.
<!-- : "systems have properties that only become apparent when their components are integrated and operate together". -->
We therefore cannot judge a sociotechnical system by its parts, or in isolation.
Evaluating sociotechnical systems thus requires assessment of the entire system in use.
<!-- We should evaluate the system as a whole, not as separate components. -->

What a full system evaluation looks like in practice, depends on the system properties.
Still, irrespective of the system specifics, there are certain standards for evaluating systems.
The 'International Organization for Standardization' (ISO) and 'International Electrotechnical Commission' (IEC) collectively publish 'Information technology' vocabularies, which include definitions of evaluation practices [@iso2015].
A set of two of these practices are relevant here: verification and validation (V&V).
Roughly stated, verification asks 'was the system built well?', whereas validation asks 'was the right system built?'.
These two terms are further detailed by the 'Institute of Electrical and Electronics Engineers' (IEEE), which routinely publishes versions of the 'Standard for System, Software, and Hardware Verification and Validation'. \nocite{ieee2025}
We will explore and operationalize the verification and validation standards for imputation methodology.

<!-- ### Verification & validation of systems -->

<!-- ### Building and evaluating imputation models  -->


<!-- In computer science, software is a system. -->
<!-- "A system is a purposeful collection of interrelated components of different kinds (e.g., "hardware, software, and human elements" p. 552] that work together to deliver a set of services to the system owner and its users." [@sommerville2015, p. 556] -->
<!-- Systems engineering is dedicated to the study and development of systems "to support human activities" [@sommerville2015, p. 552]. -->
<!-- "Systems that include software fall into two categories: 1. Technical computer-based systems [and] 2 Sociotechnical systems". [@sommerville2015, p. 552] -->
<!-- "For example, this book was created through a sociotechnical publishing system that includes various processes (creation, editing, layout, etc.) and technical systems (Microsoft Word and Excel, Adobe Illustrator, Indesign, etc.)." [@sommerville2015, p. 552] -->
<!-- "Sociotechnical systems: include one or more technical systems but, crucially, also people, who understand the purpose of the system, within the system itself. Sociotechnical systems have defined operational processes, and people (the operators) are inherent parts of the system." [@sommerville2015, p. 552].  -->
<!-- So imputing is a sociotechnical system, not technical system, while mice is technical.  -->
<!-- "sociotech systems "do not just include software and hardware but also people, processes, and organizational policies" p. 556] -->
<!-- That means that mice is a technical system, whereas the imputation workflow is sociotechnical and depends on other components. -->
<!-- "The successful functioning of each system component depends on the functioning of other components" [@sommerville2015, p. 556].  -->
<!-- "Systems have properties that only become apparent when their components are integrated and operate together." -->
<!-- For imputation this means that there should be ‘interoperability’ with other systems, such as ggplot for viz, and stats packages for analyses.  -->
<!-- "a sociotechnical system as a set of layers, where each layer contributes, in some way, to the functioning of the system. At the core is a software-intensive technical system and its operational processes" (p.557) -->


<!-- Why is validation needed?  -->
<!-- "Sociotechnical systems are complex systems, which means that it is practically impossible to have a complete understanding, in advance, of their behavior. This complexity leads to three important characteristics of sociotechnical systems: 1. They have emergent properties that are properties of the system as a whole, rather than associated with individual parts of the system. Emergent properties depend on both the system components and the relationships between them. Some of these relationships only come into existence when the system is integrated from its components, so the emergent properties can only be evaluated at that time. Security and dependability are examples of important emergent system properties. 2. They are nondeterministic, so that when presented with a specific input, they may not always produce the same output. The system’s behavior depends on the human operators, and people do not always react in the same way. Furthermore, use of the system may create new relationships between the system components and hence change its emergent behavior. 3. The system’s success criteria are subjective rather than objective. The extent to which the system supports organizational objectives does not just depend on the system itself. It also depends on the stability of these objectives, the relationships" [@sommerville2015, p. 558] -->



<!-- "Systems engineering (White et al. 1993; Stevens et al. 1998; Thayer 2002) is the activity of designing entire systems, taking into account the characteristics of hardware, software, and human elements of these systems. Systems engineering includes everything to do with procuring, specifying, developing, deploying, operating, and maintaining both technical and sociotechnical systems. Systems engineers have to consider the capabilities of hardware and software as well as the system’s interactions with users and its environment. They must think about the system’s services, the constraints under which the system must be built and operated, and the ways in which the system is used." [@sommerville2015, p. 552] -->

<!-- "system is more than simply the sum of its parts. … A useful working definition of these types of system is as follows: A system is a purposeful collection of interrelated components of different kinds that work together to deliver a set of services to the system owner and its users." [@sommerville2015, p. 556] -->

<!-- "Human, social, and organizational issues affect the requirements and design of software systems". -->

<!-- Validation is often socio-technical: it combines technical inspection with human judgment and domain knowledge. -->

<!-- There are standards for the evaluation of a system: verification & validation [@ieee2025]. -->
<!-- V&V is needed when the 'high road' of analytical derivations and proofs are impossible or unfeasible. -->
<!-- Instead, computer scientists use computational evaluation to assess systems. -->
<!-- Verification and validation (V&V) is a process for the evaluation of systems, used when the 'high road' of formal proofs is blocked. -->
<!-- It is framework for checking whether we have both built the system correctly as well as built the correct system. -->

System evaluation through verification is about whether the system conforms to its specifications.
The technical definition of verification is "confirmation, through the provision of objective evidence, that specified requirements have been fulfilled" [@iso2017, def. 3.4538].
In other words, does the system produce the expected output?
We can verify a system's output if we have a clearly defined input–output relation.
For a given input, we then already know what the correct output should be, and we can review whether the system reproduces that output. 
A typical form of verification are unit tests in software.
Unit tests check if individual function in software packages return the correct output when a certain known input is supplied.
<!-- If we plug in an input with a known truth, do we get the right answer in return? -->
<!-- In other words: if we plug in an input with a known truth, do we get the right answer in return? -->
<!-- Verification asks 'was the system built right?', whereas validation asks 'was the right system built?'.  -->
<!-- So with verification, we can check the quality of a system by plugging in an input with a known output.  -->
<!-- Do we get the correct output in return?  -->
<!-- TODO: add back?? For imputation methodology, verification is what we do with simulation studies and with unit tests in software.  -->
<!-- We want to check whether the system (or the method in this case) conforms to the requirements that we set (e.g. accuracy).  -->
<!-- Verification is about conformity to specifications, usually before or independent of real-world use. -->
Verification is typically carried out before or independent of real‑world use.
Note, therefore, that "a system could be verified to meet the stated requirements, yet be unsuitable for operation by the actual users" [@iso2017, def. 3.4538].
For evaluation of systems in actual use, we need validation.

Validation concerns whether the system is suitable for applied use.
Validation is "the set of activities ensuring and gaining confidence that a system is able to accomplish its intended use, goals and objectives" [@iso2017, def. 3.4500]. 
Validation evaluates how well a system satisfies the user needs.
<!-- ... "satisfy intended use and user needs" [@ieee2017, def. 3.4500]. -->
<!-- Then validation, on the other hand, asks whether the system is suitable for operation by the actual users in a specific intended use or application.  -->
<!-- Is a system able to accomplish its intended use?  -->
Typical validation processes consists of use cases and usability testing, to evaluate whether users have all they need to use the system. 
Validation combines technical inspection with human judgment and domain knowledge.
That's why validation is a crucial element in evaluating sociotechnical systems, such as imputation processes.
<!-- If we want to verify and validate, however, we first have to operationalize the two standards for  -->
<!-- In stats, it's proving that a statistical model or analytical procedure behaves as intended under real-world operating conditions. -->
<!-- A validation test is a "test to determine whether an implemented system fulfils [sic.] its specified requirements" [@iso2015, def. 3.4501]. -->
<!-- TODO: add back?? For imputation methodology, it is tools for users to evaluate their imputation workflow with specific data (and, optionally, their intended analysis models). -->
In the next paragraphs, I will operationalize the standards of verification and validation for evaluating imputation methodology specifically.
I define two evaluation approaches, that together provide a toolbox for V&V of imputation workflows: computational evaluation and graphical evaluation.

<!-- We will operationalize verification and validation by  -->
<!-- This dissertation describes computational and graphical evaluation tools. -->
Computational evaluation is a largely quantitative evaluation approach.
It covers the use of metrics, tests, and simulations to evaluate properties of a system.
The practice of computational evaluation combines *effectiveness* (i.e., did the process yield the correct result, e.g., accuracy, precision, recall, etc.), *system quality* (e.g., speed, coverage of all possible results, etc.) and, importantly, *user utility* (e.g., happiness, productivity, etc.) [@manning2008].
Computational evaluation can therefore contribute both to verification as well as validation of systems.
A type of computational evaluation for verification, for example, is the use of simulation studies to quantify the performance of statistical methods.
For validation, computational evaluation can be useful, for example, to quantify a certain method's fault rate in applied use.
The term 'computational evaluation' is not specifically defined for the field of statistics, but it could be useful. 
I want to plant a flag: how can we define computational evaluation in the context of imputation methodology?

Since 'computational evaluation' is not defined for statistics, there is no direct definition to use to define computational evaluation for imputation methodology.
Computational evaluation stems originally from information retrieval research [see e.g. @wiki].
One definition of computational evaluation is "to determine the quality of solutions attainable" [@dudek2004] 
Another definition of computational evaluation is "the process of ensuring an algorithmic solution is a good one: that it is fit for purpose" [@curzon2014].
A working definition for imputation methodology is: the systematic assessment of algorithmic behavior and data-level outputs of imputation procedures.
In this dissertation I will use computational evaluation as a suite of tools to investigate the domains of algorithmic stability, data plausibility, and user burden, next to inferential validity.
<!-- , focused on: algorithmic stability (convergence, failure modes), sensitivity to modeling choices, plausibility and coherence of imputed values, and usability for applied researchers.  -->
These aspects are often already taken into account by imputers, but I try to systematize and operationalize these aspects that are often informal or *ad hoc*. 
Please note that computational evaluation does not replace statistical evaluation; it extends the scope of the evaluations.
Computational evaluation encompasses all systematic, computer-based evaluation tools, including inferential estimates and statistical performance measures such as bias and confidence validity.
Computational evaluation goes beyond statistical evaluation.
Even if we know the process yields correct inferences, we can evaluate the 'fit' of the solution. 
For example, a certain model may be statistically valid, but take too long to converge for real-time use in a production pipeline or patient consult.
Computational evaluation will then tell us that this statistically valid method is not fit for purpose. 

<!-- Statistical evaluation is important, e.g. to quantify  bias and variance of estimators/procedures, but not the focus of this dissertation. -->
<!-- Computational evaluation is something to check *conditional on* acceptable statistical properties, and does not replace statistical evaluation.  -->
<!-- Translated to statistics, a model may be statistically valid, but not fit for purpose.  -->
<!-- This may happen, for example, when a model takes too long to converge to be used in real-time in a production pipeline or patient consult. -->

<!-- Computational evaluation encompasses a range of systematic, computer-based evaluation tools such as numerical experiments or simulation studies. -->

<!-- ### What are graphical and computational evaluation? (= operationalization of V&V) -->

<!-- [TODO: edit] -->
Graphical evaluation is the second approach I will employ.
This is a largely qualitative type of evaluation.
Graphical evaluation stands in a long tradition within the scientific discipline of statistics.
Many data analysis workflows encourage visual inspection prior to and after modeling.
For example, statistical assumptions are often checked by means of diagnostic visualization.
<!-- What is computational evaluation and diagnostic visualization? -->
<!-- - Computational (quantitative) evaluation – metrics, tests, simulations. -->
<!-- - Graphical (qualitative) evaluation – diagnostic visualization/visual inspection. -->
<!-- Computational evaluation encompasses a range of systematic, computer-based evaluation tools such as numerical experiments or simulation studies. -->
<!-- Computational evaluation is use of metrics, tests, and simulations to evaluate properties of the system with minimal human judgment. -->
This practice is diagnostic because the purpose is to identify patterns and problems, such as mismatches between the data and model assumptions.
<!-- instead of descriptive/summaries. -->
Graphical evaluation helps users understand the system’s behavior and judge whether it’s acceptable for their needs.
As a working definition, I will consider graphical evaluation to be the use of plots and figures to communicate system behavior to end users.
For imputation methodology, graphical evaluation is mostly applicable as validation tool.
Graphical evaluation can aid imputers in assessing user utility, such as usability of the system, appropriateness of the methods, and plausibility of the imputations.
To show how computational and graphical evaluation can be useful in practice, the next section outlines a typical imputation workflow with `mice`.

<!-- Computational evaluation is originally from information retrieval research [see e.g. @wiki]. -->
<!-- The practice of computational evaluation combines *effectiveness* (i.e., did the process yield the correct result, e.g., accuracy, precision, recall, etc.), *system quality* (e.g., speed, coverage of all possible results, etc.) and, importantly, *user utility* (e.g., happiness, productivity, etc.) [@manning2008]. -->
<!-- The term 'computational evaluation' is not specifically defined for the field of statistics, but it could be useful.  -->
<!-- In this dissertation, I want to plant a flag: how can we define 'computational evaluation' in the context of imputation methodology? -->

<!-- Since the term is not defined for statistics, there is no definition to use for the computational evaluation of imputation methodology. -->
<!-- One definition of computational evaluation is "to determine the quality of solutions attainable" [@dudek2004]  -->
<!-- Another definition of computational evaluation is "the process of ensuring an algorithmic solution is a good one: that it is fit for purpose" [@curzon2014]. -->
<!-- Translated to statistics, a model may be statistically valid, but not fit for purpose.  -->
<!-- For example, computations that take too long to converge for use in a production pipeline or real-time use in a patient consultation. -->

<!-- Computational evaluation is not equal to statistical evaluation.  -->
<!-- Computational evaluation goes beyond statistical evaluation. -->
<!-- Statistical evaluation is important, e.g. to quantify  bias and variance of estimators/procedures, but not the focus of this dissertation. -->
<!-- Computational evaluation is something to check *conditional on* acceptable statistical properties, and does not replace statistical evaluation.  -->
<!-- Dimensions of computational evaluation: e.g. inferential validity, algorithmic behavior, data-level plausibility, user utility, ... -->
<!-- - which of these is the problem when we use PMM with parse data? on the one hand, it might lead to imputations that are so close that the CI is too narrow and confidence validity is ar risk. on the other hand, it might lead to implausible imputed values for cases with missingness in the sparse region. -->
<!-- Working definition: *systematic assessment of the algorithmic behavior and data-level outputs of imputation procedures*, focused on: algorithmic stability (convergence, failure modes), sensitivity to modeling choices, plausibility and coherence of imputed values, and usability for applied researchers.  -->
<!-- In this dissertation I will use computational evaluation as a suite of tools to investigate the domains of algorithmic stability, data plausibility, and user burden, next to inferential validity. -->
<!-- These aspects are often already taken into account by imputers, but I try to systematize and operationalize these aspects that are often informal or *ad hoc*.  -->

<!-- Computational (quantitative) evaluation – metrics, tests, simulations -->
<!-- Graphical (qualitative) evaluation – diagnostic visualization/visual inspection -->

<!-- - [in simulation study kun je waarheid maken, maar in de praktijk moet je aannames doen. die aannames zijn belangrijk, juist omdat ze niet/ten dele te bewijzen zijn] -->
<!-- - [what is a simulation study? add a brief methodological background section on simulation studies in statistics?] -->



### What is involved in a `mice` workflow? (or: human in the loop) 

The R package `mice` enables researchers with missing data problems to correct for differences due to missingness and maintain the appropriate level of uncertainty. 
@fig-steps shows an imputation workflow with `mice`.
<!-- requires human input -->
The flowchart shows four steps in the imputation workflow where human judgement is encouraged: inspecting the missingness, defining imputation models, inspecting algorithmic convergence, and inspecting imputed values. 
Not depicted in the flowchart are steps that require external stakeholders (e.g., involving subject-matter experts).
There are some decisions that you, as imputer, implicitly or explicitly make.
The imputation function `mice()` will happily produce imputations with its defaults, but not necessarily "good" imputations.

::: {#fig-steps}

```{mermaid}
%%| fig-height: 6

flowchart TB
    inc[/"Incomplete data"/] --> miss[\"Inspect missingness"/] 
    subgraph build[" "]
      miss
      mod
    end
    miss --> mod[\"`Define imputation model(s)`"/]
    mod --> imp[[Run imputation algorithm]]
    imp --> imps["Imputations<br> $$\quad(1 \dots m)$$"]
    imps --> conv
    subgraph eval[" "]
      direction TB
      conv[\"`Inspect convergence`"/] 
      check[\"`Inspect imputed values`"/]
      conv <--> check
    end
    conv -- "✘ non-convergence" --> imp
    check -- "✘ misfit" --> mod
    check -- "✓ algorithmic convergence<br>✓ imputation model fit" --> analyses
    analyses[\"`Run analyses`"/] --> mira["Extract<br>estimates"]
    mira --> pool(["Pool estimates"])
    pool --> mipo["Pooled estimate"]
    inc@{ shape: doc}
    imps@{ shape: docs}
    analyses@{ shape: procs}
    mira@{ shape: tri}
```


<!-- - Giswerk/gebrek aan controle leidt to suboptimale estimates -->
<!-- merge edges: https://stackoverflow.com/questions/51367234/fusing-arrows-sideways-in-mermaid-diagrams -->

`\fignote{Processes that require human intervention are depicted with trapezoids in the flowchart. Notably, these steps occur in pairs: before imputation, the user can inspect the missingness and define imputation models; after imputation, the user can evaluate the output of the imputation algorithm.}`{=latex} 


Flowchart of multiple imputation with `mice`

:::

<!-- Not depicted in the flowchart are steps that require external information (e.g., involving subject-matter stakeholders). Statistical evaluation is mainly focused on the relation between the incomplete data and pooled estimates. Computational evaluation is in every trapezoid: processes that require human intervention. In the first box, the question is: 'how can we model the missingness?', in the second box, the question is: 'do the imputation models fit the data?'. Missing in the graph: drawing inference with pooled estimate, and use external info after inspecting the missingness to involve all stakeholders (CRISP-DM steps). -->

<!-- #### Missing data -->
A data analyst faced with incomplete data should not start imputing right away.
They should first ask themselves: what kind of missingness am I dealing with? 
Inspect the patterns of missingness and consider which missingness mechanism(s) might be at play.
A missing data pattern plot tells you where missingness occurs (which variables, which cases) and which variables tend to be missing together.
For definitive conclusions about the missing data mechanism, however, we need external information.

Imputation with `mice` assumes ignorable missingness.
MCAR and MAR are modeling assumptions, not empirically verifiable facts.
In practice, it it impossible to determinately differentiate between MCAR and MNAR.
But specific MAR mechanisms may become apparent through computational and graphical evaluation (e.g., by calculating or plotting associations between observed data and missingness indicators).
If MNAR is suspect, use dedicated tools and/or design sensitivity analyses to assess how robust your conclusions are.
If MAR mechanisms show up, include the relevant relations into the imputation models.

<!-- #### Methods -->
Imputation models consist of imputation methods and imputation model predictors.
For each incomplete variable, `mice` asks you to specify an imputation method. 
This is a choice of the functional form of the imputation model (e.g., logistic regression for dichotomous variables).
How do we know which functional form to choose?
The simplest option is to accept `mice`'s defaults, which are motivated by simulation studies and pragmatism.
For example, the default method for continuous variables is the semi-parametric method `pmm`: predictive mean matching. 
With `pmm`, observed data entries are used as donors when imputing missing entries, conveniently yielding imputed values that lie within the range of the observed data.
Diverting from these defaults might be useful in case of big, wide, or sparse data.
That is, some methods can be computationally inefficient with big data (large $n$, large $p$), mathematically undefined with wide data ($n < p$), or yield suboptimal imputations because of a lack of donors in sparse data ranges.
Moreover, if the column type in the incomplete data is not correctly specified, `mice` will assign incorrect imputation methods.
Therefore, inspecting the distribution of each incomplete variable is advised.
You can use bar charts, histograms, and density plots of the observed part of the variable to assess the distribution of the incomplete variables and determine imputation methods.
Visual inspection can also be used to check whether there is skew or spikes (e.g., structural zeros) that require transformations.
In short, the imputation method determines the distribution of the imputed values, which should match the distribution of the observed values to at least some extent.

<!-- - Model building: how do we know which functional form to choose? -->
<!--   - rely on defaults, tested in simulation studies  -->
<!--   - assess the distribution of the incomplete variable (e.g., visual inspection) -->
<!--   - ...? (maybe ad transformations?) -->

<!-- #### Predictors -->
The next major decision concerns the predictor matrix: which variables should be used to impute which?
Some common sources of input are the associations assumed by the analysis model, associations in the observed data, associations with missingness indicators, and external input and design information.
If you already know your primary analysis model (e.g., multivariate regression), it is good practice to include all analysis model predictors and outcomes in the imputation models. 
Using the associations implied by the analysis model may safeguard against uncongeniality [@meng1994].
Roughly speaking, the concept of congeniality refers to how well the imputation model and complete data model 'fit together', and could stem from the same data-generating process.
When an analysis model variable is omitted as a predictor from the imputation model, we are implicitly assuming that its association with the imputed variable is zero [@rubin1996].
If we constrain these parameters to zero in the imputations, we are systematically suppressing relations in the imputed data (i.e., biasing the regression coefficients in the analysis model towards zero).
We should therefore always use the complete data model---if available---when building imputation models.
If there is already one specific data analysis model for the effect of scientific interest that you have in mind, please using consider substantive model compatible fully conditional specification [SMC-FCS, @bartlett2015]. 
SMC-FCS is optimized for known analysis model models: we assume a complete data model and derive the imputations from there.
Imputation with `mice`, however, is complete data 'agnostic'.
We do not need to know the model of scientific interest upfront.
Instead, we can rely on other sources of information for choosing imputation model predictors.
<!-- Well, fully conditional specification is substantive model agnostic.  -->
<!-- So we build an imputation model based on the most complex analysis model that we might want to test.  -->
<!-- Then take the most complex possible model and use that, because if you would take the simplest model, then that would implicitly mean you are constraining parameters, systematically suppressing relations. -->
<!-- Don't forget to add the effect of interest in your model of scientific interest.  -->
<!-- Otherwise, you are constraining the relation between the variables to be zero.  -->

<!-- Apart from the complete data model, there are other sources of information for choosing imputation model predictors. -->
Deciding which associations to include in the imputation models can be a data-driven process.
A data-driven approach would fit many modern data science pipelines, where the imputed data may be used for several exploratory and/or unsupervised analyses. 
But also when the analysis model is known, it is advised to inspect associations in the incomplete data when choosing imputation model predictors.
You may include a broader set of predictors than strictly needed for the complete data model by adopting 'auxiliary variables' (i.e., extra imputation model predictors that are not part of the analysis model or variables of interest).
For example, we can include predictors that are strongly associated with the incomplete variable: ["include an auxiliary variable if its correlation with the main variable is ≥0.5", @nguyen2021, p. 4].
Not just associations with the incomplete variable itself may be used to select imputation model predictors.
We can also use the association of the missingness indicator with other variables in the data.
Predictors that explain missingness can help you approximate MAR or correct for design-related patterns.
Other design-related patterns require expert knowledge e.g., about branching or which external information should be included to mitigate MNAR.
Choosing imputation model predictors encodes your beliefs about what information is relevant for reconstructing the incomplete data and capturing missingness mechanisms.

<!-- - Model building: how do we know which imputation model predictors to select? -->
<!--   - association of incomplete variable with other variables in the data ["include an auxiliary variable if its correlation with the main variable is ≥0.5 (in absolute value) [25]" @nguyen2021] -->
<!--   - association of missingness indicator with other variables in the data  -->
<!--   - external input (e.g., branching patterns, or expert knowledge to correct for MNAR) -->
<!--   - Take the analysis model (if available) as starting point for imputation workflow, for congeneality -->
<!--   - ...? -->

<!-- #### Other parameters -->
After specifying the imputation model methods and predictors, there are still some optional parameters to consider changing in the imputation process.
For example, the number of imputations (argument `m` in the `mice()` function) and number of iterations in the imputation algorithm (argument `maxit`) may affect the quality of the imputations and resulting statistical inferences.
For guidance on these parameters, see e.g. @vanbuuren2018 and the `mice` documentation.
We can now run the imputation algorithm and evaluate the output.

<!-- #### Imputations -->
After a successful `mice` run, you need to ask whether the imputation process behaved adequately.
Some post hoc evaluation tools include algorithm-level diagnostics (e.g., traceplots of key parameters over iterations to assess algorithmic convergence), visual inspection of the distribution of the imputed values (e.g., to identify mismatch between observed and imputed data distributions), and sensitivity analyses (e.g., via over-imputation, which temporarily treats some observed values as missing to compare imputations to the true values).
These evaluations are neither fully automated nor purely objective. 
They involve building and reading plots, interpreting diagnostics, and deciding what degree of misfit is tolerable for your research aims.
<!-- - TODO: maybe add this back? Model evaluation: how do we assess imputation model misfit? -->
<!--   - fit of the model to the observed data -->
<!--   - non-convergence in the algorithm  -->
<!--   - mismatch between observed and imputed data distributions (e.g., visual inspection) [@vanbuuren2018] -->
<!--   - ...? -->
Without graphical or computational diagnostic for non-convergence, users might analyze imputed values of non-converged chain.
Another question to consider is: do the imputed values lie within the range of the observed values?
For statistical validity this is not needed. 
Imputation theory does not require the imputed values to be plausible. 
Rubin [-@rubin1976; -@rubin1987] developed the methodology to get correct population-level inferences from incomplete samples, not at the individual case-level within the sample. 
<!-- [TODO: consider adding that since then, data analysis has changed] -->
Bluntly stated: imputation theorists don't care for the imputed values themselves, as long as they result in statistically valid inferences.
But end-users (e.g. clinicians) often do care for plausibility.
For example, imputing negative values for age will yield 'unrealistic' imputed values. 

Taken together, these decisions show that a `mice` workflow is not a push-button solution. 
It is a modeling exercise in which the user is involved in model building and evaluation.
Imputation with `mice` is a sociotechnical process.
<!-- When we apply this terminology to imputation workflows, we can conclude that -->
<!-- A statistical software package can be thought of as a system. -->
<!-- In computer science, a system is a collection of interrelated components (software, hardware, and people) that together deliver services to users [@sommerville2015, p. 556]. -->
While `mice` is a technical system (i.e., a piece of software with algorithms to generate imputations) applications of `mice` are sociotechnical.
In practice, imputation workflows include `mice`, the imputation script, the analysis script, visualizations, and the researcher interpreting the output and deciding what to accept.
<!-- Imputing is a sociotechnical system, which includes more components than just `mice`. -->
<!-- Successful use of `mice` depends on the usability of the software in practice. -->
Human input makes imputation workflows subjective to individual choices and preferences.
<!-- How, then, do we know which decisions are the right ones? -->
<!-- The defaults provide a starting point, but the adequacy of the imputations—and therefore the validity of your inferences—ultimately depends on how thoughtfully you make and review these human inputs. -->
Since "systems have properties that only become apparent when their components are integrated and operate together", we should evaluate the imputation workflow not as separate functions, but as a whole.
For imputation methods this means that they should work in practice, not just in simulations. 
For such systems, analytic guarantees (e.g., asymptotic unbiasedness of MI) are not enough. 
We need computational and graphical checks on the whole workflow. 


<!-- But what if that model is not (yet) available?  -->
<!-- But what if the analysis model is unknown?  --> 

<!-- [TODO: add back in?] But how to know it works in practice?  -->
<!-- [TODO: add back in?] We need assumptions. -->
<!-- [TODO: add back in?] Many assumptions inherent to a model-based technique like MI cannot be tested without the missing data itself. -->
<!-- [TODO: add back in?] So, like assumptions for GLM, we look at the data to evaluate the appropriateness of our chosen model. -->
<!-- [TODO: add back in?] Similarly, we need to evaluate the choice of imputation models for signs of assumption violations. -->
<!-- [TODO: add back in?] Some assumption checks are visual inspection, some are quantitative, some need external info. -->
